---
# Github SSH Keys to Authorized Keys Variables
github_user: dkolb
always_download_keys: yes

# k3s variables
k3s_version: v1.21.1+k3s1
ansible_user: ubuntu
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable servicelb --disable traefik --etcd-expose-metrics true"
extra_agent_args: ""