---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  chart: sealed-secrets
  version: "~1.16.1"
  targetNamespace: kube-system
  repo: https://bitnami-labs.github.io/sealed-secrets 
  valuesContent: |-
    ingress:
        enabled: false
        annotations: {}
        path: /v1/cert.pem
        hosts:
            - sealed-secrets.home.krinchan.com