apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: metallb
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: metallb
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "192.168.86.80-192.168.86.100"
    controller:
      image:
        repository: metallb/controller
        tag: "v0.9.5"
    speaker:
      image:
        repository: metallb/speaker
        tag: "v0.9.5"