apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
  values:
    config-inline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "192.168.86.80-192.168.86.100"
    controller:
      image:
        tag: "0.9.5"
    speaker:
      image:
        tag: "0.9.5"