apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: metallb
spec:
  chart: metallb
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: metallb
  valuesContent: |-
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "192.168.86.80-192.168.86.100"
    controller:
      image:
        repository: metallb/controller
        tag: "v0.9.5"
    speaker:
      image:
        repository: metallb/speaker
        tag: "v0.9.5"