---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dkub
  namespace: pihole
spec:
  url: https://dkolb.github.io/charts/
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  chart:
    spec:
      chart: pihole
      version: "1.8.29"
      sourceRef:
        kind: HelmRepository
        name: dkub
        namespace: pihole
  values:
  # https://github.com/MoJo2600/pihole-kubernetes/blob/master/charts/pihole/values.yaml
    image:
      repository: "pihole/pihole"
      tag: "latest"
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "192.168.86.81"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-services
    serviceWeb:
      type: ClusterIP
    ingress:
      enabled: true
      path: /
      hosts:
        - pihole.home.krinchan.com
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    DNS1: "8.8.8.8"
    DNS2: "8.8.4.4"
    doh:
      enabled: true
      name: cloudflared
      repository: crazymax/cloudflared
      tag: latest
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-volume-claim