---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pihole-nfs
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /mnt/InternalNvmeStorage/k8sVolumes/pihole
    server: "192.168.86.2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: pihole-nfs
