---
apiVersion: v1
kind: Namespace
metadata:
  name: homebridge
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: homebridge-nfs
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /mnt/InternalNvmeStorage/k8sVolumes/homebridge
    server: "192.168.86.2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-volume-claim
  namespace: homebridge
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: homebridge-nfs
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homebridge-stack
  namespace: homebridge
spec:
  repo: https://k8s-at-home.com/charts/
  chart: homebridge
  version: "~2.0.0"
  valuesContent: |-
    image:
      tag: latest
    env:
      TZ: America/New_York
      PUID: 5000
      PGID: 5000
    hostNetwork: true
    persistence:
      config:
        enabled: true
        existingClaim: homebridge-volume-claim
    ingress:
      enabled: true
      hosts:
        - host: homebridge.home.krinchan.com
          paths:
            - path: /
      annotations: {}