---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik
spec:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  targetNamespace: traefik
  interval: 10m
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesContent: |-
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "192.168.86.80"
