---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-backup
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: minecraft-backup-daily
  namespace: minecraft-backup 
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 600 #10 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3 #default
  failedJobsHistoryLimit: 3 #default is 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: minecraft-backup-daily
              image: ghcr.io/dkolb/minecraft-backup:edge
              imagePullPolicy: IfNotPresent
              args:
                - "--source 'crimsoncraft-ftp:/crimsoncraft.zip'"
                - "--destination 'do-space:crimsoncraft-backups/'" 
                - "-v"
                - "--dry-run"
              volumeMounts:
                - name: rclone
                  mountPath: "/root/.config/rclone"
          volumes:
            - name: rclone
              secret:
                secretName: minecraft-backup-config
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcrio-credentials