---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-backup
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minecraft-backup
  namespace: minecraft-backup
spec:
  repo: https://dkolb.github.io/charts/
  chart: minecraft-backup
  valuesContent: |-
    imagePullSecrets:
      - name: ghcrio-credentials
    source: "crimsoncraft-ftp:/crimsoncraft.zip"
    destination: "do-space:crimsoncraft-backups/"