apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-backup-config
  namespace: minecraft-backup
spec:
  encryptedData:
    rclone.conf: AgCsjoc0T6eaA7zheh4DI1vN63iK3C31SrUeKay7QhoVNvegc/o2kN+nxP81SaHpjmdjAHndKOV+MHZPHseh3IimQTKpNrJngqtv+PRh3JqlR75iNz2SdU+Gl37yGPsSW4bPxbxKlSA1WIMrVdkyjP7TNgDpXY9ay23+mKJUFghvHJjvKCLPeZsUxzT9HCv81cpBHaXlxXAlYyzea2Tb42ury9hQ4U/pmoHBI2ccqXYVDNTBFBRTsOcO/pboALLIFLjc1Ap913AG8iMxwIz00onuRPN9FaO+0C48FfgJoFGzyBfV019hAbQD1vS1IAfTqHMpoJZ5MFnlHGs8juoZ2fGFtt5n59ppaKMyM5UrMom8S44AwZWhZR69QjEoZAVI0fLNGTKcPshi7IK4OrbX26UVzEkd8oaMaSM8OeEWUgpOEFtdg9vgnZL/RZkDCqWsH4l7j6F7vygY6bPMvf0vkidAyK0qaxbExEU1OptTgm3xA+FOZwguq20V6D35xGJzyUwuD/cPRLujjWHZH1u+bsxtNz7/NVjoYRIXOTb4Xtl6Sd9/hRV9lMIN8ByZgQTWqDKMbjlodt8ZQlNNFUgr84xhBiEFLbJ4VrVKs9qNgH6hzzvZPL4dlFMLUwtUYM40z6TfIg/SBrTJjSLlOSG8zYE3SXzRerxFiP7gK62A/QLk6b59/sGN62Izfh0OO7UdBZskqbwWRS2PKbewhAl1oWvmSbSm7U2Q3qevF1KkcEUc7wlaa08WtpFsRo82U6hbXWcUD/F4qg32yNoNdUKTd6dX1V3TgKPyqnqCmj+H9ew120yb1I3QVoRl8eSBj77jbBkZrU3kRuZraLgWAmLu98uJUQVyAgXzBF719q7ky9Ph9Z8eIJACuxzgwzIihOKyAo1TxPz2g/EQV+liSWSUm3rO5UouhefSQcTKZBx1r0Osbw4ZJskrLoLCFMlpbxV2qDv2/WtSGUh3BQFngTJErmAJkqRnZbtRErwXnZNawQWfbM15IJIInUXSxmvx1YTQdlgzjQ+QqtDt3JFR3eMn8arfFc7p0y9b2QX/1utK9G929j+RCLKrNqlaI+8XXUdQv/PRiTaTEpbF6TwjpGuhX7TcqvUa0Ggwvcm3/46Jg5k1WUKxrtbZUo/eGdjwplZn2XHApLvm4qTwpwSmYvn20e7xyWH0gdbeeML8nf1q20TMTgRRjjHdQIXF6DxO3FDEhQOZLzkB0NT8G23LMGQK6l7BQoF7eImYsak+PcmSsyAFjZxjmqmBnHDBvEPo+LwNGbetXAcbAndtD6fdbZMpfV7v83PjF84B80vpe82WxNDgc2Tj1dHhAT2NPJnQO6AaIrQdOg3/y+M=
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-backup-config
      namespace: minecraft-backup

