apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: prometheus
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "~13.13"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus
  values:
    defaultRules:
      kubeApiserverSlos: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheusOperator:
      configReloaderCpu: 200m
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alertmanager.home.krinchan.com
        paths:
          - /
        pathType: ImplementationSpecific
    grafana:
      ingress:
        enabled: true
        hosts:
          - grafana.home.krinchan.com
        paths:
          - /
        pathType: ImplementationSpecific
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.home.krinchan.com
        paths:
          - /
        pathType: ImplementationSpecific
      prometheusSpec:
        resources:
            requests:
              cpu: "500m"