---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 10m
  chart:
    spec:
        chart: sealed-secrets
        version: "1.15.0-r1"
        sourceRef:
          kind: HelmRepository
          name: sealed-secrets
          namespace: sealed-secrets
  values:
      ingress:
          enabled: false
          annotations: {}
          path: /v1/cert.pem
          hosts:
              - sealed-secrets.home.krinchan.com