---
- name: Bespoke setup
  hosts: k3s_cluster
  gather_facts: yes
  become: no
  roles:
    - role: hostname
    - role: authorize_github_keys
    - role: install_additional_packages

- import_playbook: k3s-ansible/site.yml

- name: Get kube config
  hosts: master
  gather_facts: yes
  become: no
  roles:
    - role: fetch_kube_config